title: ASTROANDES
description: Website for the computational astrophysics research group from Universidad de los Andes (Colombia)
author: ASTROANDES
github: https://github.com/astroandes
about: Computational astrophysics research group of Universidad de los Andes (Colombia)
disqus_shortname: astroandes
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

urls:
    - text: Members
      url: /members/
    - text: Projects
      url: /projects/
    - text: Posts
      url: /posts/

url: "https://astroandes.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
